# Generated by Django 6.0.5 on 2026-06-08 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrutins', '0001_initial'),
        ('vote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionscrutin',
            name='nom_electeur',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inscriptionscrutin',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inscriptionscrutin',
            name='electeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('inscription_demande', "Demande d'inscription"), ('inscription_acceptee', 'Inscription acceptée'), ('inscription_refusee', 'Inscription refusée')], max_length=30)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.inscriptionscrutin')),
                ('scrutin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrutins.scrutin')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
