# Generated by Django 6.0.5 on 2026-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_demandeadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('electeur', 'Electeur')], default='electeur', max_length=20, null=True),
        ),
    ]
