# Generated by Django 6.0.5 on 2026-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadmin',
            name='motif',
            field=models.TextField(default=' aucun motif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandeadmin',
            name='organisation',
            field=models.CharField(default='aucun motif', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandeadmin',
            name='cni',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demandeadmin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='demandeadmin',
            name='nom',
            field=models.CharField(max_length=150),
        ),
    ]
