# Generated by Django 6.0.5 on 2026-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_demandeadmin_motif_demandeadmin_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
