# Generated by Django 6.0.5 on 2026-05-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrutins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidats/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='scrutins.scrutin')),
            ],
        ),
    ]
