# Generated by Django 6.0.5 on 2026-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='poste',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
